name: Lint workflows

on:
  push:
    branches:
      - main
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'

jobs:
  lint:
    name: Lint workflows
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          mise_toml: |
            [tools]
            pinact = "latest"
            actionlint = "latest"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pinact
        run: |
          pinact run --check

      - name: Run actionlint
        run: |
          actionlint
