name: Lint workflows

on:
  push:
    branches:
      - main
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'
  pull_request:
    branches:
      - main
    paths:
      - '.github/**/*.yml'
      - '.github/**/*.yaml'

jobs:
  lint:
    name: Lint workflows
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          mise_toml: |
            [tools]
            pinact = "latest"
            actionlint = "latest"
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run pinact
        run: |
          pinact run --check

      - name: Run actionlint
        run: |
          actionlint
